export const Strings ={
    pokemonList: "Pokemon List",
    home: "Home",
    myPokemonList: "My Pokemon List",
    weCanNotFindThatPage: "We can't find that page",
    returnHome: "Return Home",
    Pokemon:"Pokémon App",
    networkError:"network Error",
    prev:"Prev",
    next:"Next",
    nickname: "Enter the Pokemon Nickname",
    catch:"Catch",
    berries:"Berries",
    contest:"Contest",
    evolution:"Evolution",
    moves:"Moves",
    encounter:"Encounter",
    viewDetail:"View Detail",
    remove:"Remove",
    processing:"Processing...",
    noDataAvailable:"No data available",
    welcomeToThePokémonApp:"Welcome to the Pokémon App!",
    startYourPokémonJourneyHere:"Start your Pokémon journey here.",
    clickThisButton:"Click this button",
    successful:"Successful"
}
